# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/txzing/Desktop/micro_7020/system_wrapper/vivado_proj/vivado_proj.srcs/sources_1/bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xci
# IP: The module: 'system_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/txzing/Desktop/micro_7020/system_wrapper/vivado_proj/vivado_proj.gen/sources_1/bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/txzing/Desktop/micro_7020/system_wrapper/vivado_proj/vivado_proj.srcs/sources_1/bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xci
# IP: The module: 'system_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/txzing/Desktop/micro_7020/system_wrapper/vivado_proj/vivado_proj.gen/sources_1/bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
